# docker-compose.yml

version: '3'

services:
  web:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

  test-runner:
    build:
      context: .
    volumes:
      - .:/code
    depends_on:
      - web
    environment:
      - SELENIUM_HOST=web
      - SELENIUM_PORT=4444
    command: pytest --maxfail=1 --disable-warnings -q
